services:
  web:
    image: kyliroco/ssda2026:latest
    pull_policy: always
    environment:
      APP_PORT: "6767"
      DATABASE_URL: postgresql://game_user:change_me_now@db:5432/generate_or_not
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - app_net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: generate_or_not
      POSTGRES_USER: game_user
      POSTGRES_PASSWORD: change_me_now
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U game_user -d generate_or_not"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
